basePath: /
definitions:
  domain.Pdf:
    properties:
      created_at:
        type: string
      file_name:
        type: string
      file_path:
        type: string
      file_size:
        type: integer
      id:
        type: integer
      updated_at:
        type: string
    required:
    - file_name
    - file_path
    - file_size
    type: object
  rest.MergeRequest:
    properties:
      fileNames:
        items:
          type: string
        type: array
    type: object
  rest.PdfEditRequest:
    properties:
      file_name:
        type: string
      operation:
        type: string
      params:
        additionalProperties: true
        type: object
    type: object
  rest.ResponseError:
    properties:
      message:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: This is a sample server for Go Clean Architecture.
  title: Go Clean Arch API
  version: "1.0"
paths:
  /pdf/compress/{file_name}:
    post:
      consumes:
      - application/json
      description: Compresses the PDF file specified by the file name parameter.
      parameters:
      - description: The name of the PDF file to compress
        in: path
        name: file_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Compressed PDF file details
          schema:
            $ref: '#/definitions/domain.Pdf'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Compress a PDF file
      tags:
      - PDFs
  /pdf/edit:
    put:
      consumes:
      - application/json
      description: Request body for editing a PDF file (rotate, add image, add SVG,
        etc.)
      parameters:
      - description: PDF Edit Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.PdfEditRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Edited PDF
          schema:
            $ref: '#/definitions/domain.Pdf'
        "400":
          description: Invalid request body or missing parameters
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      tags:
      - PDFs
  /pdf/fetch:
    get:
      consumes:
      - application/json
      description: Fetches a list of PDFs based on the provided query parameter `num`
      parameters:
      - default: 10
        description: Number of PDFs to fetch
        in: query
        name: num
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of PDFs
          schema:
            items:
              $ref: '#/definitions/domain.Pdf'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Fetch a list of PDFs
      tags:
      - PDFs
  /pdf/merge:
    post:
      consumes:
      - application/json
      description: Merge the provided list of PDF files into a single file
      parameters:
      - description: List of file names to be merged
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.MergeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: The merged PDF file
          schema:
            $ref: '#/definitions/domain.Pdf'
        "422":
          description: Unprocessable entity error details
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Merge PDF files
      tags:
      - PDFs
  /pdf/split/{file_name}:
    post:
      consumes:
      - application/json
      description: Splits the given PDF file into multiple files based on its content
      parameters:
      - description: Name of the PDF file to split
        in: path
        name: file_name
        required: true
        type: string
      - default: 1
        description: Number of pages per split
        in: query
        name: pages_per_split
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Array of split PDF files
          schema:
            items:
              $ref: '#/definitions/domain.Pdf'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Split a PDF file
      tags:
      - PDFs
  /pdf/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload one or more PDF files and save them to the server
      parameters:
      - description: PDF files to be uploaded
        in: formData
        name: pdfs
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: List of uploaded PDFs
          schema:
            items:
              $ref: '#/definitions/domain.Pdf'
            type: array
        "400":
          description: Invalid request, error details
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload PDF files
      tags:
      - PDFs
swagger: "2.0"
