// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/bxcodec/go-clean-arch/domain"
	mock "github.com/stretchr/testify/mock"
)

// PdfRepository is an autogenerated mock type for the PdfRepository type
type PdfRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PdfRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *PdfRepository) Fetch(ctx context.Context, num int64) ([]domain.Pdf, error) {
	ret := _m.Called(ctx, num)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []domain.Pdf
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Pdf, error)); ok {
		return rf(ctx, num)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Pdf); ok {
		r0 = rf(ctx, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Pdf)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(ctx, num)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PdfRepository) GetByFileName(ctx context.Context, filename string) (domain.Pdf, error) {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for GetByfilename")
	}

	var r0 domain.Pdf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Pdf, error)); ok {
		return rf(ctx, filename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Pdf); ok {
		r0 = rf(ctx, filename)
	} else {
		r0 = ret.Get(0).(domain.Pdf)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTitle provides a mock function with given fields: ctx, title
func (_m *PdfRepository) GetByTitle(ctx context.Context, title string) (domain.Pdf, error) {
	ret := _m.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for GetByTitle")
	}

	var r0 domain.Pdf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Pdf, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Pdf); ok {
		r0 = rf(ctx, title)
	} else {
		r0 = ret.Get(0).(domain.Pdf)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, a
func (_m *PdfRepository) Store(ctx context.Context, a *domain.Pdf) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Pdf) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *PdfRepository) StoreAll(ctx context.Context, a []*domain.Pdf) (err error) {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Pdf) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, ar
func (_m *PdfRepository) Update(ctx context.Context, ar *domain.Pdf) error {
	ret := _m.Called(ctx, ar)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Pdf) error); ok {
		r0 = rf(ctx, ar)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPdfRepository creates a new instance of PdfRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPdfRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PdfRepository {
	mock := &PdfRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
